#JDBC Configutation for Database Connection
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://db01.c1suaoqsgxev.eu-north-1.rds.amazonaws.com:3306/accounts?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
jdbc.username=admin
jdbc.password=admin1234

#Memcached Configuration For Active and StandBy Hosdb01.c1suaoqsgxev.eu-north-1.rds.amazonaws.comt
#For Active Host
memcached.active.host=0001.cm.sqmmjv.eun1.cache.amazonaws.com
memcached.active.port=11211
#For StandBy Host
memcached.standBy.host=0001.cm.sqmmjv.eun1.cache.amazonaws.com
memcached.standBy.port=11211

#RabbitMq Configuration
rabbitmq.address=amqps://b-3ec80f57-de99-4d5e-a2a2-914533236238.mq.eu-north-1.on.aws
rabbitmq.port=5671
rabbitmq.username=guest
rabbitmq.password=guest

#Elasticesearch Configuration
elasticsearch.host =vprosearch01
elasticsearch.port =9300
elasticsearch.cluster=vprofile
elasticsearch.node=vprofilenode
